import type { NextPage } from 'next'
import Head from 'next/head'
import { useEffect } from 'react'
import { supabase } from './utilities/constants'

const Home: NextPage = () => {
  useEffect(() => {
    supabase.auth.onAuthStateChange((event, session) => {
      console.log('event', event)
      console.log('session', session)
    })
  }, [])

  const googleSignin = async () => {
    const res = await supabase.auth.signIn({ provider: 'google' })
    console.log('res', res)
  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen flex justify-center items-center">
        <button className="py-2 px-8 shadow focus:shadow-none" onClick={googleSignin}>
          Google Login
        </button>
      </main>
    </div>
  )
}

export default Home
